parameters:
    event.oauth.user_provider.class: Event\UserBundle\Oauth\UserProvider

services:
    event.oauth.user_provider:
        class: %event.oauth.user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebookId }]