EventEventBundle_homepage:
    path:     /
    defaults: { _controller: "EventEventBundle:Home:index" }
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login